### ISSUE TITLE
Sendemail TLS Problem with Exchange 2019 

### ISSUE THREAD

**Issue by Manuel1948** [mogaal/sendemail#20]
```
C:\scripts>sendemail.exe -t error@xxx.xx -f error@xxx.xx -u test -m test -s xxx.xx:587 -xu xxx -xp ppp -v -v -o tls=yes
Jun 09 23:19:14 i5-3470s sendemail.exe[23352]: DEBUG => Connecting to xxx.xx:587
Jun 09 23:19:14 i5-3470s sendemail.exe[23352]: DEBUG => My IP address is: 192.168.138.48
Jun 09 23:19:14 i5-3470s sendemail.exe[23352]: DEBUG => evalSMTPresponse() - Found SMTP success code: 220
Jun 09 23:19:14 i5-3470s sendemail.exe[23352]: SUCCESS => Received:     220 xxx.xx Microsoft ESMTP MAIL Service ready at Tue, 9 Jun 2020 23:19:12 +0200
Jun 09 23:19:14 i5-3470s sendemail.exe[23352]: INFO => Sending:         EHLO i5-3470s
Jun 09 23:19:14 i5-3470s sendemail.exe[23352]: DEBUG => evalSMTPresponse() - Found SMTP success code: 250
Jun 09 23:19:14 i5-3470s sendemail.exe[23352]: SUCCESS => Received:     250-xxx.xx Hello [IP-hidden], 250-SIZE 37748736, 250-PIPELINING, 250-DSN, 250-ENHANCEDSTATUSCODES, 250-STARTTLS, 250-AUTH GSSAPI NTLM, 250-8BITMIME, 250-BINARYMIME, 250-CHUNKING, 250 SMTPUTF8
Jun 09 23:19:14 i5-3470s sendemail.exe[23352]: DEBUG => The remote SMTP server supports TLS :)
Jun 09 23:19:14 i5-3470s sendemail.exe[23352]: DEBUG => Starting TLS
Jun 09 23:19:14 i5-3470s sendemail.exe[23352]: INFO => Sending:         STARTTLS
Jun 09 23:19:14 i5-3470s sendemail.exe[23352]: DEBUG => evalSMTPresponse() - Found SMTP success code: 220
Jun 09 23:19:14 i5-3470s sendemail.exe[23352]: SUCCESS => Received:     220 2.0.0 SMTP server ready
Jun 09 23:19:15 i5-3470s sendemail.exe[23352]: ERROR => **TLS setup failed: SSL connect attempt failed because of handshake problemserror:00000000:lib(0):func(0):reason(0)**
```

Everytime excatly this error with sendemail, why and what is the error trying to say?

**Comment by panguluriravikanth** [comment]
Any solution you got for thiis

**Comment by levi-jcbs** [comment]
Check out this unmerged Pull Request: https://github.com/mogaal/sendemail/pull/22/commits/dd0ec96aed8af3ff9c069cec222551f9b5d8f601

I did the Change for myself in my code, and it worked for me.

**Comment by abhi-io** [comment]
This worked for me
1. uninstall sendemail 
2. ```apt install apt-transport-https libio-socket-inet6-perl -y```
3. ```curl  'http://ftp.cn.debian.org/debian/pool/main/s/sendemail/sendemail_1.56-5.2~bpo12+1_all.deb' -O  ```
4. ```dpkg -i  sendemail_1.56-5.2~bpo12+1_all.deb```

**Comment by Manuel1948** [comment]
> This worked for me
> 
> 1. uninstall sendemail
> 2. `apt install apt-transport-https libio-socket-inet6-perl -y`
> 3. `curl  'http://ftp.cn.debian.org/debian/pool/main/s/sendemail/sendemail_1.56-5.2~bpo12+1_all.deb' -O  `
> 4. `dpkg -i  sendemail_1.56-5.2~bpo12+1_all.deb`

not only that the solution is coming 4 years too late, it is also not helpful for a Windows machine, which you can see clearly in the log from the path and executable 🤣

thank you for trying 😅
