### ISSUE TITLE
email least file 

### ISSUE THREAD

**Issue by silentminer22** [mogaal/sendemail#25]
wanted to ask if there is any option of sending emails to an email least of a any file type

**Comment by levi-jcbs** [comment]
Hey,

You can send to multiple adresses by placing them one behind the other, separated by spaces. If their are all in a file, you have to parse them that way.

For example, you have a file with one email address in each line:
`./sendEmail -t $( cat list.txt | tr '\r\n' ' ' ) ...`
Or an file, where the addresses are listed in the following format: `"address@one.com","address@two.com","address@three.com"`
`./sendEmail -t $( cat list2.txt |  tr -d '\"' | tr "," " " ) ...`

I hope I could help you,
Levi

**Comment by silentminer22** [comment]
thanks
