### ISSUE TITLE
message body (HTML)

### ISSUE THREAD

**Issue by silentminer22** [mogaal/sendemail#26]
hello please help with sending a message body as html

like the -m option how can i send email as an html template

**Comment by levi-jcbs** [comment]
Hello,
I think this is not relevant enough to create an issue, but here is what you asked for:

1. Create a html template:
```html
<!DOCTYPE html>
<html>
<head>
<style>
/* STYLE FOR BODY, JUST FOR EXAMPLE */
body{
color:black;
background-color:white;
}
/* CSS STYLESHEET */
</style>
</head>
<body>
<!-- INSERT MESSAGE CONTENT HERE -->
</body>
</html>
```

2. Don't forget setting message type in sendEmail command:
```bash
./sendEmail \
-o message-content-type=html    // SETTING MESSAGE TYPE TO HTML \
-o message-charset=UTF-8        // SETTING TEXT TYPE TO UTF8 \
...
```

(3. Including HTML as file to message:)
```bash
./sendEmail \
-m "$( cat htmlmessage.html )"   // IF YOU ARE USING BASH/SHELL \
...
```

I hope I could help you,
Levi

**Comment by silentminer22** [comment]
thank u so much i really appreciate Levi
