### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by d7n1** [mogaal/sendemail#28]
i have added the argument with this line of code  -f dan9****@gmail.com -t dan07******@gmail.com -u test -m testing -s smtp.gmail.com:587 -xu dan9****@gmail.com -xp my email password -o tls=yes . it does not work at all after i try to set a task schedular on window by start the sendEmail.exe program why this happen to me :(

**Comment by levi-jcbs** [comment]
Please take a short look hat #23, therefore you have to configure your Gmail Account a bit to let it work.
Also remember, that there where known issues with SSL encrypted sending in the past.

Because sendemail is out of maintenance, please do also consider to use a more up-to-date tool like mutt.
